export const DATA = [
  {
    id: 1,
    first_name: "Nial",
    last_name: "Massen",
    email: "nmassen0@businesswire.com",
    gender: "Male",
  },
  {
    id: 2,
    first_name: "Jephthah",
    last_name: "Heathfield",
    email: "jheathfield1@mapy.cz",
    gender: "Male",
  },
  {
    id: 3,
    first_name: "Humfried",
    last_name: "Juden",
    email: "hjuden2@unesco.org",
    gender: "Male",
  },
  {
    id: 4,
    first_name: "Edyth",
    last_name: "Leeves",
    email: "eleeves3@adobe.com",
    gender: "Female",
  },
  {
    id: 5,
    first_name: "Keith",
    last_name: "Paridge",
    email: "kparidge4@washingtonpost.com",
    gender: "Male",
  },
  {
    id: 6,
    first_name: "Kathleen",
    last_name: "Kohler",
    email: "kkohler5@discovery.com",
    gender: "Agender",
  },
  {
    id: 7,
    first_name: "Matthus",
    last_name: "Heaker",
    email: "mheaker6@exblog.jp",
    gender: "Male",
  },
  {
    id: 8,
    first_name: "Roldan",
    last_name: "Canet",
    email: "rcanet7@goodreads.com",
    gender: "Male",
  },
  {
    id: 9,
    first_name: "Blinnie",
    last_name: "Checchetelli",
    email: "bchecchetelli8@drupal.org",
    gender: "Bigender",
  },
  {
    id: 10,
    first_name: "Gilli",
    last_name: "Peegrem",
    email: "gpeegrem9@hugedomains.com",
    gender: "Female",
  },
  {
    id: 11,
    first_name: "Jacinta",
    last_name: "Croker",
    email: "jcrokera@tumblr.com",
    gender: "Female",
  },
  {
    id: 12,
    first_name: "Rudie",
    last_name: "Warlow",
    email: "rwarlowb@mozilla.com",
    gender: "Male",
  },
  {
    id: 13,
    first_name: "Marthe",
    last_name: "Quiddihy",
    email: "mquiddihyc@prnewswire.com",
    gender: "Female",
  },
  {
    id: 14,
    first_name: "Dunn",
    last_name: "Swanborough",
    email: "dswanboroughd@usatoday.com",
    gender: "Male",
  },
  {
    id: 15,
    first_name: "Dorri",
    last_name: "Ettles",
    email: "dettlese@angelfire.com",
    gender: "Female",
  },
  {
    id: 16,
    first_name: "Marjorie",
    last_name: "Farbrother",
    email: "mfarbrotherf@nature.com",
    gender: "Female",
  },
  {
    id: 17,
    first_name: "Stanislas",
    last_name: "Kilbee",
    email: "skilbeeg@slideshare.net",
    gender: "Male",
  },
  {
    id: 18,
    first_name: "Nevsa",
    last_name: "Buttler",
    email: "nbuttlerh@parallels.com",
    gender: "Female",
  },
  {
    id: 19,
    first_name: "Robbin",
    last_name: "Whitmore",
    email: "rwhitmorei@un.org",
    gender: "Female",
  },
  {
    id: 20,
    first_name: "Cherice",
    last_name: "Ding",
    email: "cdingj@vinaora.com",
    gender: "Non-binary",
  },
  {
    id: 21,
    first_name: "Danny",
    last_name: "Lambin",
    email: "dlambink@flavors.me",
    gender: "Male",
  },
  {
    id: 22,
    first_name: "Carry",
    last_name: "Neilly",
    email: "cneillyl@multiply.com",
    gender: "Female",
  },
  {
    id: 23,
    first_name: "Jyoti",
    last_name: "Bottleson",
    email: "jbottlesonm@dailymail.co.uk",
    gender: "Female",
  },
  {
    id: 24,
    first_name: "Hank",
    last_name: "McCuis",
    email: "hmccuisn@php.net",
    gender: "Male",
  },
  {
    id: 25,
    first_name: "Allyn",
    last_name: "Boman",
    email: "abomano@cbslocal.com",
    gender: "Female",
  },
  {
    id: 26,
    first_name: "Lynnett",
    last_name: "Klein",
    email: "lkleinp@opera.com",
    gender: "Female",
  },
  {
    id: 27,
    first_name: "Timothea",
    last_name: "Cianelli",
    email: "tcianelliq@amazon.co.jp",
    gender: "Female",
  },
  {
    id: 28,
    first_name: "Oralle",
    last_name: "Fabbro",
    email: "ofabbror@samsung.com",
    gender: "Female",
  },
  {
    id: 29,
    first_name: "Sanderson",
    last_name: "Grinikhin",
    email: "sgrinikhins@ustream.tv",
    gender: "Male",
  },
  {
    id: 30,
    first_name: "Ronnie",
    last_name: "Phillipps",
    email: "rphillippst@example.com",
    gender: "Female",
  },
];
